### ISSUE TITLE
Change icon sizing

### ISSUE THREAD

**Issue by DanBuchan** [DanBrooker/file-icons#149]
Is there a trivial way to change the size of the icons as they appear in the tree view and tabs?

**Comment by DanBrooker** [comment]
Not really, this would kind of work but probably isn't that nice
```css
.icon-file-text, .icon-file-directory, .icon-file-media, .icon-book {
  &:before { font-size: large }
}
```
