### ISSUE TITLE
There is no icon for SVG

### ISSUE THREAD

**Issue by nkt** [DanBrooker/file-icons#196]
Here is svg logo: https://github.com/gilbarbara/logos/blob/master/logos/svg.svg

**Comment by sanusart** [comment]
There is one in icomoon font - `\eae3`:

You can use it via your `styles.less` like this for now. 

````less
// file-icons overrides
@import 'packages/file-icons/styles/icons';
@import 'packages/file-icons/styles/colors';
@import "packages/file-icons/styles/items";

.icon-file-text {
  &[data-name$=".svg"]:before {
    .icomoon;
    content: '\eae3';
    .dark-yellow;
  }
}
````
