### ISSUE TITLE
Change the color of the tab icons in your stylesheet

### ISSUE THREAD

**Issue by LordZane** [DanBrooker/file-icons#255]
If the setting for Tab Pane Icon is checked, icons show in tabs like you would expect. However I could not find a way to change the color of them, EXCEPT if I uncheck Tab Pane Icon, then any icons I changed the color of in my styles.less would still show, and using the modified color
![screenshot 5](https://cloud.githubusercontent.com/assets/8398815/12054770/352251a4-aef4-11e5-877d-a5bb69c06812.png)
![screenshot 6](https://cloud.githubusercontent.com/assets/8398815/12054771/352cb978-aef4-11e5-9004-e703ba5a24b5.png)

**Comment by Alhadis** [comment]
Yikes, that's kinda confusing.

Try putting this into your user stylesheet:
```less
@import "packages/file-icons/styles/items";

.file-icons-tab-pane-icon @{pane-tab-selector}:before{
	color: (Whatever-your-desired-colour is)
}
```

I know that selector's not very intuitive, so I'm adding a new variable for it in the next release. You'll then be able to target it with this:
```less
@import "packages/file-icons/styles/items";

@{pane-tab-override}:before{
}
```

Does that help?
