### ISSUE TITLE
Custom tab icon not working

### ISSUE THREAD

**Issue by tomitrescak** [DanBrooker/file-icons#277]
Thanks for this awesome plugin. I have a bit of issue to make the custom icons work with the tab view. While the color is changed properly, the original icon is maintained. All works in treeview as expected. Following is an example of my configuration:

```less
@import "packages/file-icons/styles/colors"; // to use the colours
@import "packages/file-icons/styles/icons";  // to use the defined icons
@import "packages/file-icons/styles/items";

.container-icon { .fa; content: "\f0f2"}

&[data-name$="container.ts"]           { .medium-red;             } // Colours icon and filename
&[data-name$="container.ts"]:before   { .container-icon; .medium-red; } // Colours icon only  
```

The container icon and color is modified in the trreview, but the tabview is showin the original typescript icon, but the changed color of the text.

**Comment by tomitrescak** [comment]
Solved by marking styles as important

```less
@import "packages/file-icons/styles/colors"; // to use the colours
@import "packages/file-icons/styles/icons";  // to use the defined icons
@import "packages/file-icons/styles/items";

.container-icon { .fa; content: "\f0f2"}

&[data-name$="container.ts"]           { .medium-red;             } // Colours icon and filename
&[data-name$="container.ts"]:before   { .container-icon!important; .medium-red!important; } // Colours icon only  
```
