### ISSUE TITLE
Misaligned icons on Material Atom UI

### ISSUE THREAD

**Issue by ZakariaRidouh** [DanBrooker/file-icons#295]
![Image](https://cloud.githubusercontent.com/assets/11602629/13511656/e9db4938-e14a-11e5-9013-e3e39c9c19d4.png)
The icons are misaligned on the [Material Atom UI](https://github.com/silvestreh/atom-material-ui).
Thanks!

**Comment by Alhadis** [comment]
Hey mate,

Strange, I'm unable to reproduce this issue (on either Mac OS or Windows 10). Are you using the latest versions of File Icons and Atom Material? :)

Also, a similar issue was reported in the past: [one user suggested](https://github.com/DanBrooker/file-icons/issues/253#issuecomment-184177457) it might've been the fault of a (now removed) theme option to hide icons in tab bars.

As a *very* rough guess, I'd say your configuration settings still has the old setting enabled. Could you pop your user `config.cson` open and copy us the contents of the `"atom-material-ui"` key, please? :-)

**Comment by ZakariaRidouh** [comment]
@Alhadis sure, here you go!
```
  "atom-material-ui":
    colors:
      abaseColor:
        red: 87
        green: 107
        blue: 119
        alpha: 1
      accentColor:
        red: 157
        green: 105
        blue: 75
        alpha: 1
      genAccent: true
    fonts: {}
    tabs:
      tintedTabBar: true
    treeView:
      blendTabs: true
    ui:
      panelContrast: true
      panelShadows: true
```

**Comment by Alhadis** [comment]
Does uninstalling and reinstalling the Material UI theme have any effect?

**Comment by ZakariaRidouh** [comment]
Hmm, just reinstalled and the icons are still misaligned
![screen shot 2016-03-03 at 9 58 42 pm](https://cloud.githubusercontent.com/assets/11602629/13519298/3442f2e2-e18b-11e5-8587-8319de78b7b9.png)
.

**Comment by Alhadis** [comment]
Okay, I copied the exact settings you're using into my own config file... and I was unable to see any difference.

Could you kick the developer tools open and inspect the CSS properties being applied to the icons? For reference, here's how it appears for me:
<img src="https://cloud.githubusercontent.com/assets/2346707/13519499/6ec90ad6-e22c-11e5-8319-1e3eaa026788.png" alt=""/>

**Comment by ZakariaRidouh** [comment]
Here it is :smile:
![screen shot 2016-03-04 at 11 41 12 am](https://cloud.githubusercontent.com/assets/11602629/13538219/1d7a5dd4-e1fe-11e5-8341-947b7e4dd11f.png)

**Comment by Alhadis** [comment]
Ah no, that won't help... I'll need you to inspect the actual icon itself:

1. Run the following line of code in the developer console:
```js
inspect(document.querySelector("atom-pane-container > atom-pane > ul > li.tab.sortable.active > div.title.icon"));
```
You should see the Elements explorer switch focus to the current file's tab.
2. Open the element and select its `::before` pseudo-element:
<img width="288" src="https://cloud.githubusercontent.com/assets/2346707/13538465/cdb82014-e29e-11e5-8f27-aadecef13198.png">
3. Hover over the pseudo-element with the cursor, and do a screencap. Show as much of the bottom-left panel as possible:
<img src="https://cloud.githubusercontent.com/assets/2346707/13538554/651dc3dc-e29f-11e5-9d86-48b652c279a2.png" width="783">

**Comment by ZakariaRidouh** [comment]
Thank you so very much for your help, here is the screencap of it. 
![screen shot 2016-03-04 at 12 03 00 pm](https://cloud.githubusercontent.com/assets/11602629/13538733/1ac8066a-e201-11e5-904d-91607a419ccb.png)

The weird thing is that the inspect specifier that you gave me only worked on the tabs with non file-icons icons (ie the settings tab etc.) 

Here is a screenshot of the behavior (on a tab-icons tab): 
![screen shot 2016-03-04 at 1 31 22 pm](https://cloud.githubusercontent.com/assets/11602629/13540783/6e756e36-e20d-11e5-9a8e-aa8fa13e78ae.png)

**Comment by Alhadis** [comment]
Ugh, sorry, that was a stupid idea of mine. Okay, try this:
1. Add the following CSS to your user stylesheet:
```css
.tab-bar .tab .title{
	pointer-events: auto !important;
}
```
2. Select the "Inspect Element" (:mag:) button in the top-left corner of the dev window, and pick any one of the misaligned icons. Repeat the screencap process.

The theme's set the icons to ignore clicks, which means they can't be inspected by being clicked on.
