### ISSUE TITLE
Can we make Elm icon less ugly?

### ISSUE THREAD

**Issue by gyzerok** [DanBrooker/file-icons#364]
Current version of Elm icon is extremely ugly. I have no idea how to make it better, but rising this issue in case someone have.

**Comment by Alhadis** [comment]
Uh, can you post a screenshot? It looks fine to me. Not great, but that's the fault of the language's logo more than anything.

**Comment by gyzerok** [comment]
You can see that comparing to the other icons it's soo bad. Sure, it may be issue with logo itself, but maybe we can investigate a workaround?

![screen shot 2016-05-17 at 17 10 38](https://cloud.githubusercontent.com/assets/1706020/15320433/5753ce26-1c52-11e6-9065-b41d2758aad1.png)

**Comment by Alhadis** [comment]
There's nothing wrong with the icon whatsoever. It's representing the language's logo perfectly fine.

If the logo is *that* ugly to you, you can replace it with a generic-looking code icon instead. Just put the following in your user stylesheet:

```less
@import "packages/file-icons/styles/items";
@import "packages/file-icons/styles/icons";

@{pane-tab-selector}, .icon-file-text {
	&[data-name$=".elm"]:before {
		.code-icon;
		top: 0;
	}
}
```

Which will produce something like this:

<img width="125" alt="figure-1" src="https://cloud.githubusercontent.com/assets/2346707/15320782/ab50602a-1c75-11e6-8a2c-4c2df0e2fc5a.png" />

In V2, the process for customising icons will be even easier, and there'll be no need for any `@import` rubbish. Just an FYI.

Since this is seriously subjective territory, I'm closing this as a non-issue.
