### ISSUE TITLE
ICONS: Not as shown

### ISSUE THREAD

**Issue by Paradoxicality** [DanBrooker/file-icons#397]
The icons in the image, on the package site and in atom, are not the ones that you get on the tabs. E.g. for some reason I have an elephant as my PHP file icon, which I didn't want. Either update the image on the site or change the icons.

**Comment by Alhadis** [comment]
The preview image has been outdated for a long time, and is due to be updated in v2 when the entire readme will be revised.

As for the PHP icon, [you're not the only one who prefers the old one](https://github.com/DanBrooker/file-icons/commit/f04340c3a5a33e0dfa116f1b646b8efaa7bc020c#commitcomment-16712016). Add this to your user stylesheet to bring the shield-icon back:

```less
.icon-file-text[data-name$=".php"]:before{
    font-family: "FontMfizz" !important;
}
```
