### ISSUE TITLE
Can I set a particular icon for a folder or file

### ISSUE THREAD

**Issue by cristian-sima** [DanBrooker/file-icons#399]
I have a folder which I do not want to open and to set it a `locker` icon

**Comment by Alhadis** [comment]
Add this to your user stylesheet:

```css
.directory.entry > .header > .name[data-path="FOLDER_PATH_HERE"]::before{
	content: "\f06a";
	font-family: "Octicons Regular";
}
```
Replace `FOLDER_PATH_HERE` with the full path to whatever system folder you're trying to hide. So, `/Users/guest/Documents/Notes/Hurtful Memories/` would be:

```css
.directory.entry > .header > .name[data-path="/Users/guest/Documents/Notes/Hurtful Memories/"]::before{
	content: "\f06a";
	font-family: "Octicons Regular";
}
```
You can also hide the folder by putting its name in your **Ignored Names** preference, which is located in Atom's main settings panel.

Does that help?
