### ISSUE TITLE
Python package icon

### ISSUE THREAD

**Issue by LordZane** [DanBrooker/file-icons#421]
Python packages are folders with the file `__init__.py` in them

Could you guys make it so the folder icon is replaced with a brown [package](https://octicons.github.com/icon/package/) icon from octicons (`.package-icon`)? If not, how would I go about editing my stylesheet to do this?

Thanks for all your work on this package!

**Comment by Alhadis** [comment]
I'm afraid there's no way to set a directory's icon based on its contents. The closest you'd be able to do is manually set the icon for specific paths, but you'd need to maintain that manually...

```less
.icon-file-directory[data-path$="path/to/package"]::before{
	content: "\f0c4";
	color: #8F5536;
}
```

That'll target any directory whose full filesystem path ends in `path/to/package`.

Other than that, I'm afraid there's nothing more that can be done... sorry. :S
