### ISSUE TITLE
Best method to customize that survives updates?

### ISSUE THREAD

**Issue by jkupczak** [DanBrooker/file-icons#456]
I added my own custom .woff file and added CSS to the file-icons.less, icons.less, and fonts.less files. Unfortunately, the recent update wiped all of my edits. Is there a way I can have my customizations stick around?

**Comment by Alhadis** [comment]
That's... really not a good idea. Atom packages aren't supposed to be modified by users.

Instead, Atom gives users a dedicated stylesheet where they can add whatever they damn well want without fear of it going anywhere. From the **File** menu, open **Stylesheet...** and add this to your CSS:

```less
atom-pane .tab-bar .tab .title[data-path], .icon-file-text{
	
	// Usual customisations go here
	&[data-name$=".js"]:before{
		font-family: YourCustomFont;
		content: "<Icon Codepoint>";
	}
}
```

Take note: this process is due to change completely in V2 (something which is going to require every user to update their stylesheets, but it's a necessary evil).
