### ISSUE TITLE
downgrade to old icons

### ISSUE THREAD

**Issue by attilaaronnagy** [DanBrooker/file-icons#457]
Hi!

Just received an update and the new javascript icon is horrible, it has exactly the same color as I would've made a change on the file. By quick look at it, no way to tell the difference. How can I move back to an older version or color it to red/blue/green whatever?

Thx

**Comment by Alhadis** [comment]
Hey Atilla,

Are you [referring to this](https://github.com/DanBrooker/file-icons/releases/tag/v1.7.24)? The JS icons were changed to use solid-filled variants, instead of outlines. However, the colours of the icon haven't changed. May I ask you to take a screenshot so I can see exactly what you're seeing, please?

In any case, all customisations to icons - fonts, colours, sizes - can be done by adjusting your user stylesheet. =) A few quick examples on how to do that [are here](https://github.com/DanBrooker/file-icons#customisation), and detailed information on how to use your Atom stylesheet [can be found here](http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks).

**Comment by attilaaronnagy** [comment]
Ohh yes, that change! When you work with a lots of .js file it's just way-way too much yellow. In the previous version I could easily pick the ones that i've changed, but when everything in the panel is just (exactly the same) yellow... 

Small screenshot, imagine scrolling through with hundreds of js file.

<img width="171" alt="screen shot 2016-11-15 at 15 48 57" src="https://cloud.githubusercontent.com/assets/5904511/20310147/16854036-ab4b-11e6-8366-aa6170974fa1.png">

**Comment by Alhadis** [comment]
Ah yes, I see what you mean. =) Don't worry, this is an easy fix. Just add this to your user stylesheet:

```less
@import "packages/file-icons/styles/icons";

.js-icon  { &:before{ content: "\f128"; } }
.ts-icon  { &:before{ content: "\e912"; } }
.tsx-icon { &:before{ content: "\e9d1"; } }
```

Once V2 of this package is released, however, this will become the new syntax, which is a lot cleaner:

```css
.js-icon:before  { content: "\f128"; }
.ts-icon:before  { content: "\e912"; }
.tsx-icon:before { content: "\e9d1"; }
```

I hope that helps. =) Let me know if there's anything else I can help with.
