### ISSUE TITLE
Unknow icon behaviour on my project

### ISSUE THREAD

**Issue by cloud-walker** [DanBrooker/file-icons#482]
![screen shot 2017-01-02 at 16 09 44](https://cloud.githubusercontent.com/assets/1144075/21591612/11dca124-d106-11e6-9586-9eb98bf5bdc1.png)

Why `bootstrapStore.js` should have that icon?

**Comment by Alhadis** [comment]
Because it's Bootstrap. If you want it to show a JavaScript icon, add this to your user stylesheet:

```css
.bootstrap-icon[data-name$=".js"]:before{
	font-family: Mfizz;
	content: "\f129";
}
```
