### ISSUE TITLE
Icon for Twig?

### ISSUE THREAD

**Issue by bobrocke** [DanBrooker/file-icons#95]
Can you add one for Twig, too?

**Comment by gholts** [comment]
These two make some sense to me:

[The Yii icon](http://vorillaz.github.io/devicons/#/singleicon/yii) Looks kinda twiggish...

[Font Awesome's "tree"](http://fortawesome.github.io/Font-Awesome/icon/tree/) A literal tree.

Both are pretty weak attempts at an icon for Twig. The actual "icon" looks like a sprig of green onions or grass or something (lol):

![image](https://cloud.githubusercontent.com/assets/8973794/6786845/3916450a-d154-11e4-9a1f-3eabaf1aa127.png)

Has anyone seen something like that recently? An icon for .twig files is something I'd like as well.

--

After all of that, it almost makes more sense to have the icon be the same as whatever twig is being used as a template for. Likely HTML.

**Comment by gholts** [comment]
Here's something I tried, it actually looks okay:

```less
@import "packages/file-icons/stylesheets/colors"; // to use the colours
@import "packages/file-icons/stylesheets/icons";  // to use the defined icons
@import "packages/file-icons/stylesheets/items";
.twig-icon {
    .fa;
    content: "\f1bb";
}

@{pane-tab-selector}, .icon-file-text {
  &[data-name$=".twig"]          { .medium-green;             } // Colours icon and filename
  &[data-name$=".twig"]:before   { .twig-icon; .medium-green; } // Colours icon only
  &[data-name$=".twig"]:before   { .twig-icon; .medium-green; } // Colours icon only
}
```

And the result:

![image](https://cloud.githubusercontent.com/assets/8973794/6786962/081c8c7e-d155-11e4-9c8d-2d53ad4fe03e.png)
